# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'FindBuddy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

def firebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'
  pod 'Firebase/Storage'
end

  # Pods for FindBuddy
  firebase

  target 'FindBuddyTests' do
    inherit! :search_paths
    # Pods for testing
    firebase
  end

  target 'FindBuddyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
